apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-1
  labels:
    app: gateway
    release: gw-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        release: gw-dev
    spec:
      containers:
        - name: gateway
          image: "krisawatson/gateway:1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-1
  labels:
    app: gateway
    chart: gateway-1.0.0
    release: gw-dev
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.66
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30002
    protocol: TCP
    name: gateway
  selector:
    app: gateway
    release: gw-dev
